-- =============================================================================
-- One-shot seed: parties + cheques from SHREE_SHYAM_CHEQUE (1).xlsx
-- Generated by scripts/generate_cheque_seed.py
-- Pre-req: migration 010_cheques.sql must be applied first.
-- Idempotent: ON CONFLICT DO NOTHING on parties; safe to re-run for parties,
-- but cheques will duplicate so wipe first if re-running:
--     DELETE FROM cheques;
-- =============================================================================

BEGIN;

-- 1. Parties
INSERT INTO parties (name, category) VALUES ('ABHAYA TRADERS (HORLICKS)', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('ADITHYA DISTRIBUTION (KS)', 'other') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('AJAY ASSOCIATES', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('ARIHANT HEALTH CARE', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('B.BHARATI', 'staff') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('B.RAJASEKHER REDDY', 'staff') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('B.SABARI', 'staff') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('B.SARVANI', 'staff') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('BHAVANI ENTERPRISES', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('DISHA ENTERPRISES', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('DUREX', 'other') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('G.PAUL & CO', 'other') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('G.S.K.AGENCIES', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('GOEL DRUGS', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('HI-TEC SURGICAL', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('INTELLIGENT DETTOL', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('INTELLIGENT GODREJ', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('IQFA MARKETING', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('JP LOGISTICS', 'service') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('JYOTI AGENCIES', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('LAKSHMI ENTERPRISES', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('MAHESHWARA ENTERPRISES', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('MALLIKARJUNA ENTERPRISES', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('MARUTHI AGENCIES', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('MARUTHI DISTRIBUTOR', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('MEDBLOOMS PHARMACY', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('MSWIPE', 'service') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('NAVA SANJIVANI DRUGS', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('NEHA PITTI', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('OM SAI (J&J)', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('OMER TRADERS', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('PASHUPATI MEDICAL DISTRIBUTORS', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('PATWARI PHARMA', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('PAY ONE RETAIL PRIVATE LIMITED', 'service') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('PRAKASH PHARMA DISTRIBUTORS', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('RAHUL PHARMA DISTRIBUTORS', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('RAM PHARMA', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SCOOTST (DETTOL)', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SESHA SAYANA CONSTRUCTIONS', 'other') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SHREE LEELA ENTERPRISES (LIBERTY)', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SHREE SHARADA PHARMA', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SHREE SHYAM PHARMA (NARAYANGUDA)', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SHRI JYOTHI', 'other') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SLVK AGENCIES (VOLINI)', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SREE VENKATESHWARA PHARMA', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SRI BALAJI MARKETING J&J', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SRI BALAJI TRADERS (TYNOR)', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SRI SR SENSODYNE', 'other') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SRIVEN CORP', 'other') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('SWASTIK PHARMA', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('THE NEW INDIA INSURANCE', 'other') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('THE PARAS AGENCIES', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('UMA MEDICAL CORPORATION', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('VASU VACCINES & SPECIALITY DRUGS HYD PVT LTD', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('VISHAL AGENCIES', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('VISHAL MEDICAL AGENCY', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('VISHNU & COMPANY', 'other') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('VISHNU DISTRIBUTORS', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('YASH AGENCIES', 'pharma') ON CONFLICT (name) DO NOTHING;
INSERT INTO parties (name, category) VALUES ('RM PHARMA', 'pharma') ON CONFLICT (name) DO NOTHING;

-- 2. Cheques (looked up by party name; bank_id falls back to default bank)
DO $$
DECLARE
  v_default_bank UUID := (SELECT id FROM banks WHERE is_default = true LIMIT 1);
  v_party UUID;
BEGIN
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'MARUTHI AGENCIES' LIMIT 1), v_default_bank, false, '243503', 22385.00, '2026-03-04', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'MARUTHI DISTRIBUTOR' LIMIT 1), v_default_bank, false, '243504', 14267.00, '2026-03-04', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'YASH AGENCIES' LIMIT 1), v_default_bank, false, '243505', 3064.00, '2026-03-05', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'GOEL DRUGS' LIMIT 1), v_default_bank, false, '243506', 9699.00, '2026-03-05', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'PATWARI PHARMA' LIMIT 1), v_default_bank, false, '243508', 203150.00, '2026-03-11', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'SHREE SHARADA PHARMA' LIMIT 1), v_default_bank, false, '243507', 18683.00, '2026-03-06', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'VISHNU DISTRIBUTORS' LIMIT 1), v_default_bank, false, '243509', 69764.00, '2026-03-12', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'B.RAJASEKHER REDDY' LIMIT 1), v_default_bank, false, '243510', 17496.00, '2026-03-11', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'B.BHARATI' LIMIT 1), v_default_bank, false, '243511', 15788.00, '2026-03-11', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'B.SABARI' LIMIT 1), v_default_bank, false, '243512', 5035.00, '2026-03-11', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'B.SARVANI' LIMIT 1), v_default_bank, false, '243513', 5035.00, '2026-03-11', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'SESHA SAYANA CONSTRUCTIONS' LIMIT 1), v_default_bank, false, '243514', 7472.00, '2026-03-11', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'MARUTHI AGENCIES' LIMIT 1), v_default_bank, false, '243515', 9830.00, '2026-03-17', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'MARUTHI DISTRIBUTOR' LIMIT 1), v_default_bank, false, '243516', 11720.00, '2026-03-17', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'PRAKASH PHARMA DISTRIBUTORS' LIMIT 1), v_default_bank, false, '243517', 206068.00, '2026-03-21', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'SHREE SHYAM PHARMA (NARAYANGUDA)' LIMIT 1), v_default_bank, true, NULL, 92873.00, '2026-03-16', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'RAHUL PHARMA DISTRIBUTORS' LIMIT 1), v_default_bank, true, NULL, 109032.00, '2026-03-17', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'JP LOGISTICS' LIMIT 1), v_default_bank, false, '243518', 50495.00, '2026-03-23', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'PATWARI PHARMA' LIMIT 1), v_default_bank, false, '243519', 234926.00, '2026-03-30', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'MARUTHI AGENCIES' LIMIT 1), v_default_bank, false, '243521', 12874.00, '2026-03-30', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'ARIHANT HEALTH CARE' LIMIT 1), v_default_bank, false, '243522', 21368.00, '2026-04-15', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'VISHNU & COMPANY' LIMIT 1), v_default_bank, true, NULL, 8759.00, '2026-03-31', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'PRAKASH PHARMA DISTRIBUTORS' LIMIT 1), v_default_bank, false, '243524', 86764.00, '2026-04-04', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'RAM PHARMA' LIMIT 1), v_default_bank, true, NULL, 19181.00, '2026-03-31', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'GOEL DRUGS' LIMIT 1), v_default_bank, true, NULL, 18033.00, '2026-03-31', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'RAHUL PHARMA DISTRIBUTORS' LIMIT 1), v_default_bank, false, '243525', 62763.00, '2026-04-04', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'YASH AGENCIES' LIMIT 1), v_default_bank, true, NULL, 2610.00, '2026-03-31', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'SHRI JYOTHI' LIMIT 1), v_default_bank, true, NULL, 18631.00, '2026-03-31', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'PATWARI PHARMA' LIMIT 1), v_default_bank, false, '243527', 53360.00, '2026-04-08', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'UMA MEDICAL CORPORATION' LIMIT 1), v_default_bank, false, '243528', 12577.00, '2026-04-04', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'JP LOGISTICS' LIMIT 1), v_default_bank, false, '243529', 33904.00, '2026-04-09', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'VISHNU DISTRIBUTORS' LIMIT 1), v_default_bank, false, '243530', 102250.00, '2026-04-08', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'MARUTHI DISTRIBUTOR' LIMIT 1), v_default_bank, false, '243526', 14556.00, '2026-04-06', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'B.RAJASEKHER REDDY' LIMIT 1), v_default_bank, false, '243531', 17496.00, '2026-04-10', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'B.BHARATI' LIMIT 1), v_default_bank, false, '243532', 15788.00, '2026-04-10', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'B.SABARI' LIMIT 1), v_default_bank, false, '243533', 5035.00, '2026-04-10', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'B.SARVANI' LIMIT 1), v_default_bank, false, '243534', 5035.00, '2026-04-10', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'SESHA SAYANA CONSTRUCTIONS' LIMIT 1), v_default_bank, false, '243535', 7472.00, '2026-04-10', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'SHREE SHYAM PHARMA (NARAYANGUDA)' LIMIT 1), v_default_bank, true, NULL, 61267.00, '2026-04-20', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'VISHAL MEDICAL AGENCY' LIMIT 1), v_default_bank, false, '243537', 5355.00, '2026-04-21', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'VISHAL AGENCIES' LIMIT 1), v_default_bank, false, '243538', 28139.00, '2026-04-21', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'SHREE SHARADA PHARMA' LIMIT 1), v_default_bank, false, '243539', 14180.00, '2026-04-26', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'SHREE SHARADA PHARMA' LIMIT 1), v_default_bank, false, '243540', 6004.00, '2026-04-29', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'PRAKASH PHARMA DISTRIBUTORS' LIMIT 1), v_default_bank, false, '243541', 23609.00, '2026-04-24', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'PRAKASH PHARMA DISTRIBUTORS' LIMIT 1), v_default_bank, false, '243542', 99751.00, '2026-04-26', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'YASH AGENCIES' LIMIT 1), v_default_bank, true, NULL, 4886.00, '2026-04-24', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'PATWARI PHARMA' LIMIT 1), v_default_bank, false, '243543', 78370.00, '2026-04-29', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'MARUTHI AGENCIES' LIMIT 1), v_default_bank, true, NULL, 4149.00, '2026-04-24', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'MARUTHI AGENCIES' LIMIT 1), v_default_bank, false, '243544', 14848.00, '2026-04-30', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'RAHUL PHARMA DISTRIBUTORS' LIMIT 1), v_default_bank, true, NULL, 72768.00, '2026-04-24', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'RM PHARMA' LIMIT 1), v_default_bank, false, '243545', 8843.00, '2026-05-01', NULL, 'cleared', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'JP LOGISTICS' LIMIT 1), v_default_bank, false, '243547', 27339.00, '2026-05-09', NULL, 'pending', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'VISHNU & COMPANY' LIMIT 1), v_default_bank, false, '243548', 66142.00, '2026-05-07', NULL, 'pending', NULL);
  INSERT INTO cheques (party_id, bank_id, is_online, cheque_no, amount, issue_date, clearance_date, status, remarks) VALUES ((SELECT id FROM parties WHERE name = 'VISHNU DISTRIBUTORS' LIMIT 1), v_default_bank, false, '243549', 87767.00, '2026-05-07', NULL, 'pending', NULL);
END $$;

COMMIT;

-- Verification
SELECT 'parties' AS t, COUNT(*) FROM parties
UNION ALL SELECT 'cheques', COUNT(*) FROM cheques
UNION ALL SELECT 'cheques pending',  COUNT(*) FROM cheques WHERE status = 'pending'
UNION ALL SELECT 'cheques cleared',  COUNT(*) FROM cheques WHERE status = 'cleared'
UNION ALL SELECT 'cheques cancelled', COUNT(*) FROM cheques WHERE status = 'cancelled';
